### ISSUE TITLE
error in ValueMap.h converting to a bool

### ISSUE THREAD

**Issue by pkeir** [KhronosGroup/SPIR#78]
Following the SPIRV generator build instructions from the readme, my `make` invocation fails at 10% with an error in `ValueMap.h` regarding a failure to convert to a `bool`. 

```
In file included from /home/pkeir/code/ext/khronos-opencl-spirv/llvm/lib/CodeGen/CodeGenPrepare.cpp:36:
/home/pkeir/code/ext/khronos-opencl-spirv/llvm/include/llvm/IR/ValueMap.h: In member function ‘bool llvm::ValueMap<KeyT, ValueT, Config>::hasMD() const’:
/home/pkeir/code/ext/khronos-opencl-spirv/llvm/include/llvm/IR/ValueMap.h:104:31: error: cannot convert ‘const std::unique_ptr<llvm::DenseMap<const llvm::Metadata*, llvm::TrackingMDRef> >’ to ‘bool’ in return
   bool hasMD() const { return MDMap; }
```

I'm using the build commands below. Any suggestions? 

```
git clone -b khronos/spirv-3.6.1 https://github.com/KhronosGroup/SPIRV-LLVM.git llvm
cd llvm/tools
git clone -b spirv-1.1 https://github.com/KhronosGroup/SPIR clang
cd ../..
mkdir build    && cd build 
cmake ../llvm -DLLVM_USE_LINKER=gold -DCMAKE_INSTALL_PREFIX=$PWD/../install -DCMAKE_BUILD_TYPE=Release
make -j 4 && make install
```

Thanks.

**Comment by dneto0** [comment]
I'm not a maintainer of this project.  

The offending code in ValueMap.h looks like it is doing something with a unique_ptr that newer compilers don't like.  As far as I know this SPIR generator is a fork of an older version of Clang (3.6?).  Newer versions of LLVM have changed the representation of that MDMap.

Do you know what C++ compiler you are using?  Can you downgrade?

**Comment by dneto0** [comment]
Cc: @AlexeySotkin @bader

**Comment by pkeir** [comment]
Nice suggestion, thanks. I'm working on Ubuntu 18.10 with GCC 8.2.0. I installed g++-7, changed the PATH, and it built.
